root: true

env:
  es6: true
  browser: true
  commonjs: true
  node: true
  jest: true

extends:
  [
    "htmlacademy/es6",
    "plugin:react/recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
  ]

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ["react", "import"]

settings:
  react:
    version: "16"
  import/resolver: "webpack"

globals:
  process: true

rules:
  object-curly-spacing:
    [1, "always", { "arraysInObjects": false, "objectsInObjects": false }]
