// ASYNC
export const FETCH_MOVIES_ASYNC = `FETCH_MOVIES_ASYNC`;
export const FETCH_FAVORITES_ASYNC = `FETCH_FAVORITES_ASYNC`;
export const ADD_MOVIE_TO_LIST_ASYNC = `ADD_MOVIE_TO_LIST_ASYNC`;
export const REMOVE_MOVIE_FROM_LIST_ASYNC = `REMOVE_MOVIE_FROM_LIST_ASYNC`;

// SYNC
export const FILL_MOVIES = `FILL_MOVIES`;
export const FILL_FAVORITES = `FILL_FAVORITES`;
export const ADD_MOVIE_TO_LIST = `ADD_MOVIE_TO_LIST`;
export const REMOVE_MOVIE_FROM_LIST = `REMOVE_MOVIE_FROM_LIST`;
